# Generated by Django 4.2.2 on 2023-06-20 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_customuser_options_customuser_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='confirm_password',
        ),
    ]
