# Generated by Django 4.2.2 on 2023-06-20 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_customuser_confirm_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='created',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='updated',
        ),
    ]
