# Generated by Django 4.2.2 on 2023-06-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_customuser_options_remove_customuser_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('doctor', 'DOCTOR'), ('patient', 'PATIENT')], default='doctor', max_length=10),
        ),
    ]
