# Generated by Django 4.2.2 on 2023-06-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
    ]
