# Generated by Django 4.2.2 on 2023-06-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='draft',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=4),
        ),
    ]
