# Generated by Django 4.2.2 on 2023-06-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
